"""Turn a raster image into a stitch plan.

This is an auto-digitizer. Read that word carefully: auto-digitizing is not a
solved problem, and this module is not a substitute for a human digitizer or for
Ink/Stitch's hand-tuned satin columns. What it *is* good at is bold, flat,
few-colour artwork — logos, silhouettes, line art, the kind of thing an AI image
generator produces when you ask it for flat vector art. Feed it a photograph and
you will get a dense unstitchable mess, which is a property of the problem, not
of the implementation.

The pipeline:

    image -> fit to hoop -> strip background -> quantise to N Brother threads
          -> per colour: clean mask -> underlay -> angled scanline fill
          -> contour outline -> EmbPattern -> PES

Design decisions worth knowing:

* Fill is generated by walking scan lines in the *original* coordinate space at
  the requested angle, sampling the mask along each line. Rotating the raster
  instead would resample the mask and chew up thin features.
* Every colour gets one contiguous block, so the machine stops once per colour.
* Underlay runs perpendicular to the top fill. It is what stops the fill sinking
  into the fabric, and it costs about 25% more stitches.
"""

from __future__ import annotations

import heapq
import math
from dataclasses import dataclass, field
from pathlib import Path

import numpy as np
import pyembroidery as pe
from PIL import Image, ImageFilter
from scipy import ndimage

from . import palette
from . import profile as prof

# Working resolution. 0.2 mm per pixel is finer than the machine can resolve
# (min useful stitch is ~1 mm) but keeps mask edges smooth.
MM_PER_PIXEL = 0.2


@dataclass
class TraceSettings:
    size_mm: float | None = None        # longest edge; default = fit the hoop
    colors: int = 5
    density_mm: float = 0.4             # gap between fill rows
    stitch_len_mm: float = 3.0          # max length of one stitch
    # Stitches below this are dropped. Sub-0.5 mm stitches make the needle
    # re-enter almost the same hole while thread is dragged through the eye
    # without advancing — that sawing is a leading cause of thread breaks, and
    # it also draws bobbin thread up to the surface.
    #
    # Read from the machine profile so the tracer, the validator and the
    # Ink/Stitch generators cannot drift apart on the same limit.
    min_stitch_mm: float = field(default_factory=prof.min_stitch_mm)
    # Tie-in / tie-off. Without these every run left by a trim is unanchored and
    # pulls out in wear or the wash; they have to be in the file, the machine
    # will not add them.
    lock_stitches: bool = True
    lock_mm: float = 0.8                # tie leg length (keep under 2 mm)
    min_path_mm: float = 1.5            # a run shorter than this is not worth a trim
    # Stitching pulls fabric inward, so a filled shape finishes narrower than
    # drawn. Growing each colour region slightly compensates, and the side
    # effect is deliberate: adjacent colours overlap instead of leaving a hairline
    # of bare fabric between them. 0.15-0.2 mm is the usual starting point;
    # stretchy knits want more, up to ~0.4 mm.
    pull_comp_mm: float = 0.2
    fill_angle_deg: float = 45.0
    # Tatami stagger: how many rows before the penetration phase repeats.
    # 1 disables it, which lines every row's stitches up into columns — visible
    # as ridges, and a continuous perforation the fabric can tear along.
    stagger_rows: int = 4
    underlay: bool = True
    underlay_density_mm: float = 2.0
    # Pull the underlay in from the edge so the top fill covers it completely.
    # Run to the same boundary and it peeks out along the edges — the "inset"
    # every digitizing package exposes. It also removes a stitch layer from the
    # rim, which is where overlapping passes stack up worst.
    underlay_inset_mm: float = 0.5
    outline: bool = True
    remove_background: bool = True
    bg_tolerance: int = 32
    min_region_mm2: float = 4.0         # drop specks smaller than this
    bridge_mm: float = 0.8              # hops shorter than this skip the trim
    trim_mm: float = 3.0                # only trim when travel exceeds this
    # Walk around holes rather than jump, up to this much travel.
    #
    # Tuned for a machine that does NOT trim jumps within a colour (the SE700
    # does not — you snip each float by hand). Every jump avoided is one fewer
    # float, so the budget is set against hand labour, not machine time. Swept
    # on real artwork (theoretical floor ~145 jumps): 20 mm -> 619 jumps /
    # 41 min snipping; 40 mm -> 281 / 19; 60 mm -> 198 / 13; 90 mm -> 158 / 11.
    # 60 mm reaches ~91% of the floor without piling on detour thread.
    travel_mm: float = 60.0
    # Outline stitch length. Shorter than the fill's, because an outline follows
    # curves and 3 mm chords make them visibly faceted.
    outline_stitch_mm: float = 1.5
    # Ceiling on needle penetrations per mm^2 that TRAVEL may push a cell to.
    #
    # The fill itself sits near 3/mm^2; underlay, outline and colour overlap add
    # a few more. Without a cap, travel routing piled detours onto ground it had
    # already stitched and peaked at 111/mm^2 — dense enough to break thread and
    # needles, which is precisely what the manual warns about ("stitch density
    # that is too fine, or three or more overlapping stitches").
    #
    # This trades directly against jump count and the cliff is sharp: on real
    # artwork, off -> 192 jumps but 111/mm^2 peak; 16 -> 788 jumps and 28 peak.
    # Density wins that argument. A design that snaps thread is unusable; one
    # with more floats is merely tedious to trim. 0 disables the check.
    # Read from the profile so the tracer's cap and the validator's risk line
    # cannot drift apart.
    max_density_per_mm2: float = field(
        default_factory=lambda: float(prof.design_limit("max_density_per_mm2", 16.0)))
    # How hard travel routing steers AROUND ground it has already stitched.
    #
    # This is not a trade-off dial like the cap — a little avoidance improves
    # both numbers at once, because a detour that dodges the busy corridor stays
    # under the density cap and therefore succeeds, instead of being refused and
    # turning back into a float. Measured: 0 -> 750 jumps / 27 peak;
    # 1.0 -> 557 / 22; 3.0 -> 849 / 19; 8.0 -> 1,149 / 17. Past ~1 the detours
    # grow long enough to blow the travel budget, so jumps climb again.
    travel_avoid_weight: float = 1.0
    auto_angle: bool = False            # realigning gave no gain on hole-heavy art
    margin_mm: float = 2.0              # clearance inside the field


@dataclass
class TraceReport:
    layers: list = field(default_factory=list)
    width_mm: float = 0.0
    height_mm: float = 0.0
    total_stitches: int = 0
    dropped_regions: int = 0
    quant_error: float = 0.0
    notes: list = field(default_factory=list)


# --------------------------------------------------------------------------- #
# Image preparation


def _load_and_fit(path: Path, s: TraceSettings) -> tuple[Image.Image, float]:
    """Load, orient, and scale so the design fits the hoop. Returns (rgba, mm/px)."""
    img = Image.open(path)
    try:
        from PIL import ImageOps
        img = ImageOps.exif_transpose(img)
    except Exception:
        pass
    img = img.convert("RGBA")

    field_w, field_h = prof.max_field_mm()
    usable = min(field_w, field_h) - 2 * s.margin_mm
    target_mm = min(s.size_mm, usable) if s.size_mm else usable

    scale = target_mm / max(img.width, img.height)
    px_w = max(1, int(round(img.width * scale / MM_PER_PIXEL)))
    px_h = max(1, int(round(img.height * scale / MM_PER_PIXEL)))
    img = img.resize((px_w, px_h), Image.LANCZOS)
    return img, MM_PER_PIXEL


def _strip_background(img: Image.Image, tol: int) -> Image.Image:
    """Make the background transparent.

    Uses the existing alpha channel when the image has one. Otherwise samples the
    four corners; if they agree, that colour is treated as background and removed
    with a connectivity-aware flood from the border — so an enclosed region of
    the same colour (the hole in a letter 'O' is the usual case) survives.
    """
    arr = np.array(img)
    alpha = arr[:, :, 3]
    if (alpha < 255).mean() > 0.02:
        return img  # already has meaningful transparency

    rgb = arr[:, :, :3].astype(np.int16)
    h, w = rgb.shape[:2]
    corners = np.array(
        [rgb[0, 0], rgb[0, w - 1], rgb[h - 1, 0], rgb[h - 1, w - 1]], dtype=np.int16
    )
    if corners.std(axis=0).max() > tol:
        return img  # corners disagree — no uniform background to strip

    bg = corners.mean(axis=0)
    similar = (np.abs(rgb - bg).max(axis=2) <= tol)

    # Keep only background connected to the border.
    labels, n = ndimage.label(similar)
    if n:
        border = set(labels[0, :]) | set(labels[-1, :]) | set(labels[:, 0]) | set(labels[:, -1])
        border.discard(0)
        outside = np.isin(labels, list(border))
    else:
        outside = np.zeros_like(similar)

    arr[:, :, 3] = np.where(outside, 0, 255).astype(np.uint8)
    return Image.fromarray(arr)


def _quantise(img: Image.Image, n_colors: int) -> tuple[np.ndarray, list[dict]]:
    """Reduce to n_colors and snap each to the nearest Brother thread.

    Returns (index_map, threads) where index_map is -1 for transparent pixels.
    """
    from scipy.cluster.vq import kmeans2

    arr = np.array(img)
    opaque = arr[:, :, 3] > 128
    rgb = arr[:, :, :3].astype(np.float64)

    if not opaque.any():
        raise ValueError("Image is fully transparent after background removal.")

    # Cluster ONLY the opaque pixels. Including the background — even blanked to
    # a filler colour — lets it claim palette slots and silently drop real
    # colours from the design.
    samples = rgb[opaque]
    if len(samples) > 50000:
        step = len(samples) // 50000 + 1
        samples = samples[::step]

    k = min(n_colors, len(np.unique(samples, axis=0)))
    centroids, _ = kmeans2(samples, k, minit="++", seed=0, iter=25)

    # Assign every opaque pixel to its nearest centroid.
    flat = rgb.reshape(-1, 3)
    d = ((flat[:, None, :] - centroids[None, :, :]) ** 2).sum(axis=2)
    idx = d.argmin(axis=1).astype(np.int16).reshape(rgb.shape[:2])
    idx[~opaque] = -1

    # How far the real pixels sit from the colour they were forced into. Flat
    # artwork lands near zero; photographs and gradients score high because no
    # small palette can represent them. This is the honest "is this image
    # suitable" signal, measured rather than guessed.
    assigned = centroids[idx[opaque]]
    quant_error = float(np.sqrt(((rgb[opaque] - assigned) ** 2).sum(axis=1)).mean())

    # Snap each cluster to a Brother thread — and force them to be DISTINCT.
    #
    # This is a correctness requirement, not an aesthetic one. PES merges
    # adjacent blocks that share a colour: write three layers where two share a
    # palette entry and the file reads back as two, so the machine never stops
    # between them and those layers stitch in one pass with one thread. Distinct
    # colours are what create the stops.
    threads = []
    used: set[int] = set()
    for i in range(k):
        r, g, b = (int(round(c)) for c in centroids[i])
        candidates = palette.nearest((r, g, b), 8)
        match = next((c for c in candidates if c["pec_index"] not in used),
                     candidates[0])
        used.add(match["pec_index"])
        threads.append(
            {
                "source_rgb": (r, g, b),
                "hex": match["hex"],
                "name": match["name"],
                "pec_index": match["pec_index"],
                "delta_e": match["delta_e"],
                "substituted": match is not candidates[0],
            }
        )
    return idx, threads, quant_error


def _clean_mask(mask: np.ndarray, min_px: int) -> tuple[np.ndarray, int]:
    """Despeckle and close pinholes. Returns (mask, regions_dropped).

    The opening step erodes then dilates, stripping anything narrower than the
    structuring element. That is what you want against speckle on a blobby mask
    and destructive on line art: a cat drawn in 0.7 mm outline had its face
    shattered from 10 pieces into 26 and stitched out as dashes.

    The guard is on **topology, not area**. Opening is supposed to remove small
    blobs, which lowers the region count; if it raises the count it is breaking
    structures apart instead, so it is discarded. An earlier version tested area
    loss and let this through — the damage was only 2.2% of the mask by area
    while fragmenting the outline into pieces, because a hairline break costs
    almost no pixels.
    """
    mask = ndimage.binary_closing(mask, structure=np.ones((3, 3)))
    opened = ndimage.binary_opening(mask, structure=np.ones((3, 3)))
    if opened.any():
        _, before = ndimage.label(mask)
        _, after = ndimage.label(opened)
        if after <= before:
            mask = opened
    labels, n = ndimage.label(mask)
    if n == 0:
        return mask, 0
    sizes = ndimage.sum(mask, labels, range(1, n + 1))
    keep = np.zeros(n + 1, dtype=bool)
    keep[1:] = sizes >= min_px
    dropped = int((~keep[1:]).sum())
    return keep[labels], dropped


# --------------------------------------------------------------------------- #
# Stitch generation


def _scanline_fragments(
    mask: np.ndarray, angle_deg: float, spacing_px: float, step_px: float = 0.5
) -> list[list]:
    """Split a shape into fragments that each fill in one continuous pass.

    Scan lines crossing a hole break into several segments. Naively stitching
    them in row order forces the needle across the hole on every row. Instead,
    link segments on adjacent rows that overlap; each connected group is a
    "fragment" that can be filled start to finish without ever leaving the
    shape — the standard region-fragmentation approach used by commercial
    digitizers.

    Returns a list of fragments, each a list of rows, each row a list of
    (p0, p1) segments already serpentined.
    """
    ys, xs = np.nonzero(mask)
    if len(xs) == 0:
        return []

    th = math.radians(angle_deg)
    d = np.array([math.cos(th), math.sin(th)])
    n = np.array([-math.sin(th), math.cos(th)])

    pts = np.stack([xs, ys], axis=1).astype(float)
    proj_n, proj_d = pts @ n, pts @ d
    n_min, n_max = proj_n.min(), proj_n.max()
    d_min, d_max = proj_d.min(), proj_d.max()

    h, w = mask.shape
    n_steps = int(math.floor((n_max - n_min) / spacing_px)) + 1
    t_count = int(math.ceil((d_max - d_min) / step_px)) + 1
    t = d_min + np.arange(t_count) * step_px

    rows: list[list[tuple[float, float, float, float]]] = []
    for i in range(n_steps):
        k = n_min + i * spacing_px
        px = k * n[0] + t * d[0]
        py = k * n[1] + t * d[1]
        xi = np.rint(px).astype(int)
        yi = np.rint(py).astype(int)
        valid = (xi >= 0) & (xi < w) & (yi >= 0) & (yi < h)
        inside = np.zeros(t_count, dtype=bool)
        inside[valid] = mask[yi[valid], xi[valid]]

        edges = np.diff(inside.astype(np.int8))
        starts = np.flatnonzero(edges == 1) + 1
        ends = np.flatnonzero(edges == -1)
        if inside[0]:
            starts = np.r_[0, starts]
        if inside[-1]:
            ends = np.r_[ends, t_count - 1]

        row = []
        for a, b in zip(starts, ends):
            if b > a:
                row.append((k, float(t[a]), float(t[b]), i))
        rows.append(row)

    # Link overlapping segments on adjacent rows.
    seg_ids, segs = {}, []
    for ri, row in enumerate(rows):
        for si, s in enumerate(row):
            seg_ids[(ri, si)] = len(segs)
            segs.append(s)
    parent = list(range(len(segs)))

    def find(a):
        while parent[a] != a:
            parent[a] = parent[parent[a]]
            a = parent[a]
        return a

    def union(a, b):
        ra, rb = find(a), find(b)
        if ra != rb:
            parent[rb] = ra

    for ri in range(len(rows) - 1):
        for si, s in enumerate(rows[ri]):
            for sj, s2 in enumerate(rows[ri + 1]):
                if s[1] <= s2[2] and s2[1] <= s[2]:      # t-intervals overlap
                    union(seg_ids[(ri, si)], seg_ids[(ri + 1, sj)])

    groups: dict[int, dict[int, list]] = {}
    for (ri, si), sid in seg_ids.items():
        root = find(sid)
        k, ta, tb, _ = segs[sid]
        p0 = (k * n[0] + ta * d[0], k * n[1] + ta * d[1])
        p1 = (k * n[0] + tb * d[0], k * n[1] + tb * d[1])
        groups.setdefault(root, {}).setdefault(ri, []).append((p0, p1))

    fragments = []
    for g in groups.values():
        frag = []
        for j, ri in enumerate(sorted(g)):
            line = sorted(g[ri], key=lambda s: s[0])
            if j % 2:
                line = [(b, a) for a, b in reversed(line)]
            frag.append(line)
        fragments.append(frag)
    return fragments


def _order_fragments(fragments: list[list]) -> list[list]:
    """Order fragments nearest-neighbour, so travel between them is short.

    Fragment order does not change what gets stitched, only how far the needle
    walks between the pieces — which is exactly the travel that becomes a jump.
    """
    if len(fragments) < 2:
        return fragments

    def start_of(f):
        return f[0][0][0]

    def end_of(f):
        return f[-1][-1][1]

    remaining = list(range(len(fragments)))
    cur = (0.0, 0.0)
    out = []
    while remaining:
        k = min(remaining, key=lambda i: math.dist(cur, start_of(fragments[i])))
        remaining.remove(k)
        out.append(fragments[k])
        cur = end_of(fragments[k])
    return out


def _best_fill_angle(mask: np.ndarray, spacing_px: float, candidates: int = 16
                     ) -> tuple[float, int]:
    """Pick the scan angle that splits the shape into the fewest fragments.

    Fewer fragments means fewer places the fill has to break, which is what
    actually drives jump count. An earlier attempt aligned the fill to each
    shape's principal axis instead and made things marginally worse — the axis
    says nothing about where the holes are.

    Counted on a coarse grid; the winner is then filled at full density.
    """
    coarse = max(spacing_px * 4, 2.0)
    best, best_n = 45.0, None
    for i in range(candidates):
        a = i * 180.0 / candidates
        n_frag = len(_scanline_fragments(mask, a, coarse, step_px=1.0))
        if n_frag and (best_n is None or n_frag < best_n):
            best, best_n = a, n_frag
    return best, (best_n or 0)


def _subdivide(p0, p1, max_len_px: float, phase: float = 0.0
               ) -> list[tuple[float, float]]:
    """Points from p0 (exclusive) to p1 (inclusive), at most max_len_px apart.

    `phase` (0..1) shifts where the first needle penetration falls. Varying it
    per row is what makes a fill *tatami* rather than a set of parallel lines:
    without it every row's stitches land in the same columns, which reads as
    ridges or "valleys" down the fill and — more seriously — perforates the
    fabric along continuous lines it can then tear along. Staggering scatters
    the penetrations like bricks in a wall.
    """
    dx, dy = p1[0] - p0[0], p1[1] - p0[1]
    dist = math.hypot(dx, dy)
    if dist <= 1e-9:
        return [p1]
    if max_len_px <= 0:
        return [p1]

    pts: list[tuple[float, float]] = []
    # First step is shortened by the phase; the rest are full length.
    d = max_len_px * (1.0 - phase) if phase > 0 else max_len_px
    while d < dist - 1e-9:
        f = d / dist
        pts.append((p0[0] + dx * f, p0[1] + dy * f))
        d += max_len_px
    pts.append(p1)
    return pts


def _trace_contours(mask: np.ndarray, min_len: int = 12) -> list[list[tuple[int, int]]]:
    """Moore-neighbour boundary tracing. Returns ordered contours in (x, y)."""
    padded = np.pad(mask, 1, constant_values=False)
    visited = np.zeros_like(padded, dtype=bool)
    # 8-neighbourhood, clockwise from east.
    nbrs = [(1, 0), (1, 1), (0, 1), (-1, 1), (-1, 0), (-1, -1), (0, -1), (1, -1)]
    contours = []
    h, w = padded.shape

    for y in range(1, h - 1):
        for x in range(1, w - 1):
            if not padded[y, x] or visited[y, x] or padded[y, x - 1]:
                continue  # only start on a left-edge boundary pixel
            contour = []
            cx, cy = x, y
            b_dir = 4  # came from the west
            start = (x, y)
            for _ in range(4 * mask.size):
                visited[cy, cx] = True
                contour.append((cx - 1, cy - 1))
                found = False
                for k in range(8):
                    di = (b_dir + 1 + k) % 8
                    nx, ny = cx + nbrs[di][0], cy + nbrs[di][1]
                    if padded[ny, nx]:
                        b_dir = (di + 4 + 1) % 8
                        cx, cy = nx, ny
                        found = True
                        break
                if not found or (cx, cy) == start:
                    break
            if len(contour) >= min_len:
                contours.append(contour)
    return contours


def _connector_inside(mask: np.ndarray, p0, p1, step_px: float = 1.0) -> bool:
    """Would a straight stitch from p0 to p1 stay inside the shape?"""
    h, w = mask.shape
    dist = math.hypot(p1[0] - p0[0], p1[1] - p0[1])
    n = max(2, int(dist / step_px))
    for i in range(n + 1):
        x = int(round(p0[0] + (p1[0] - p0[0]) * i / n))
        y = int(round(p0[1] + (p1[1] - p0[1]) * i / n))
        if not (0 <= x < w and 0 <= y < h) or not mask[y, x]:
            return False
    return True


def _travel_path(mask: np.ndarray, p0, p1, max_px: float,
                 density: "_Density | None" = None,
                 avoid_weight: float = 3.0) -> list | None:
    """Shortest route from p0 to p1 that never leaves the shape.

    When a fill crosses a hole, the alternative to trimming is to walk around
    the hole *inside* the shape and keep stitching. That is what commercial
    digitizers do, and on hole-heavy artwork it is the difference between a few
    hundred trims and a few thousand.

    BFS is restricted to a window around the two points, so each search is small
    even though there are thousands of them.
    """
    from collections import deque

    h, w = mask.shape

    def snap(px, py):
        """Nearest mask pixel to a rounded float coordinate.

        Segment endpoints are floats sampled along a scan line; rounding one can
        land a pixel outside the shape, and rejecting those outright made BFS
        refuse 532 of 1,972 routes on a real design — leaving the fill to break
        and jump instead of walking round the hole.
        """
        x, y = int(round(px)), int(round(py))
        if 0 <= x < w and 0 <= y < h and mask[y, x]:
            return x, y
        for r in (1, 2):
            for dy in range(-r, r + 1):
                for dx in range(-r, r + 1):
                    nx, ny = x + dx, y + dy
                    if 0 <= nx < w and 0 <= ny < h and mask[ny, nx]:
                        return nx, ny
        return None

    a = snap(*p0)
    b = snap(*p1)
    if a is None or b is None:
        return None
    x0, y0 = a
    x1, y1 = b

    direct = math.hypot(x1 - x0, y1 - y0)
    if direct > max_px:
        return None

    # The window must be able to contain the whole detour, not just the direct
    # hop. Sizing it to `direct` meant any route that had to swing wide around a
    # hole fell outside the search box and was reported as "no path" — 532 of
    # 1,972 routes on a real design. Size it to the travel budget instead, and
    # let the depth limit rather than the box bound the work.
    margin = int(max(10, max_px))
    xa, xb = max(0, min(x0, x1) - margin), min(w, max(x0, x1) + margin + 1)
    ya, yb = max(0, min(y0, y1) - margin), min(h, max(y0, y1) + margin + 1)
    sub = mask[ya:yb, xa:xb]
    sh, sw = sub.shape
    start = (y0 - ya) * sw + (x0 - xa)
    goal = (y1 - ya) * sw + (x1 - xa)

    # Dijkstra weighted by how much thread is already on the ground, not a plain
    # BFS. Steering travel AROUND stitched corridors keeps density down without
    # having to refuse the detour outright — refusing it just turns it back into
    # a jump, and jumps are floats the user has to cut by hand.
    # Two quantities, deliberately kept apart:
    #   cost  - density-weighted, decides WHICH route Dijkstra prefers
    #   glen  - true geometric length, the only thing the travel budget bounds
    #
    # Conflating them was a real bug. With avoid_weight on, every cell costs
    # 1 + weight*density, so a 55 mm route accumulated 200+ units and blew a
    # 60 mm budget that it physically fitted inside. Travel routing then failed
    # 102 times on a design whose floor was 9 runs, and the fill jumped instead.
    INF = float("inf")
    dist = np.full(sh * sw, INF, dtype=np.float64)
    glen = np.full(sh * sw, INF, dtype=np.float64)
    prev = np.full(sh * sw, -1, dtype=np.int32)
    dist[start] = 0.0
    glen[start] = 0.0
    prev[start] = start
    heap = [(0.0, start)]
    found = False
    limit = float(max_px)

    def cell_cost(gy, gx):
        if density is None or avoid_weight <= 0:
            return 1.0
        d = density.at((gx + xa, gy + ya))
        return 1.0 + avoid_weight * d

    while heap:
        cost, cur = heapq.heappop(heap)
        if cost > dist[cur]:
            continue
        if cur == goal:
            found = True
            break
        if glen[cur] >= limit:      # bound on real distance, not weighted cost
            continue
        cy, cx = divmod(cur, sw)
        for dy in (-1, 0, 1):
            ny = cy + dy
            if ny < 0 or ny >= sh:
                continue
            for dx in (-1, 0, 1):
                if dx == 0 and dy == 0:
                    continue
                nx = cx + dx
                if nx < 0 or nx >= sw or not sub[ny, nx]:
                    continue
                ni = ny * sw + nx
                span = 1.414 if dx and dy else 1.0
                nd = cost + span * cell_cost(ny, nx)
                if nd < dist[ni]:
                    dist[ni] = nd
                    glen[ni] = glen[cur] + span
                    prev[ni] = cur
                    heapq.heappush(heap, (nd, ni))
    if not found:
        return None

    path = []
    cur = goal
    while cur != start:
        cy, cx = divmod(cur, sw)
        path.append((cx + xa, cy + ya))
        cur = int(prev[cur])
    path.append((x0, y0))
    path.reverse()

    # Budget the detour against what a trim costs, rather than against the
    # direct distance. At 400 spm a trim is ~1 s of stop-cut-restart, which buys
    # roughly 6-7 stitches; a detour up to `max_px` of travel is therefore the
    # cheaper option even when it is several times the direct hop. The extra
    # stitches are invisible — they run inside the shape, in that shape's colour.
    if len(path) > max_px:
        return None

    # Collapse the pixel walk into straight runs that stay inside the shape.
    #
    # Always take the FARTHEST visible point, searching backward — that is what
    # keeps the detour short and straight. A forward scan that stops at the first
    # non-visible point hugs the pixel path instead and cost 13% more stitches
    # for no measurable speed gain. The window is capped so the cost stays
    # bounded when travel budgets are large.
    simple = [path[0]]
    n_pts = len(path)
    i = 0
    while i < n_pts - 1:
        j = min(n_pts - 1, i + 128)
        while j > i + 1 and not _connector_inside(mask, path[i], path[j]):
            j -= 1
        simple.append(path[j])
        i = j
    return simple


class _Density:
    """Running count of needle penetrations per mm^2, used to veto travel.

    Routing round a hole instead of jumping is nearly free the first time and
    ruinous the tenth: the detour lays thread through ground that is already
    stitched. Left unchecked it drove peak density to 111 penetrations/mm^2 on a
    real design — the manual's own warning about "stitch density that is too
    fine or three or more overlapping stitches", and a reliable way to break
    thread and needles.

    Cells are 1 mm. `cap` is the ceiling a detour may not push a cell past;
    the fill and underlay themselves are always allowed through.
    """

    def __init__(self, shape, mm_per_px: float, cap: float):
        self.cell_px = max(1.0, 1.0 / mm_per_px)          # 1 mm cells
        h = int(shape[0] / self.cell_px) + 2
        w = int(shape[1] / self.cell_px) + 2
        self.grid = np.zeros((h, w), dtype=np.int32)
        self.cap = cap

    def _idx(self, pt):
        return (min(self.grid.shape[0] - 1, int(pt[1] / self.cell_px)),
                min(self.grid.shape[1] - 1, int(pt[0] / self.cell_px)))

    def at(self, pt) -> int:
        r, c = self._idx(pt)
        return int(self.grid[r, c])

    def add(self, pts) -> None:
        for p in pts:
            r, c = self._idx(p)
            self.grid[r, c] += 1

    def would_exceed(self, pts) -> bool:
        if self.cap <= 0:
            return False
        for p in pts:
            r, c = self._idx(p)
            if self.grid[r, c] >= self.cap:
                return True
        return False


def _lines_to_paths(
    mask: np.ndarray, lines: list, max_len_px: float, break_px: float,
    bridge_px: float = 0.0, travel_px: float = 0.0, stagger_rows: int = 4,
    density: "_Density | None" = None, avoid_weight: float = 1.0,
) -> list[list[tuple[float, float]]]:
    """Flatten scan lines into continuous stitch paths.

    Consecutive serpentine lines sit one row apart, so they are normally
    stitched straight through rather than trimmed. The connector is only allowed
    when it **stays inside the shape** — checking distance alone is not enough
    and is actively wrong: a fill crossing the counter of an 'e', or the gap
    between two letters, would otherwise sew a solid bar straight across the
    hole. That turns crisp lettering into a black slab, and it is invisible in
    the mask (which is correct) — it only appears in the stitches.

    When the connector would leave the shape, the path breaks and the caller
    emits a trim plus a jump.
    """
    paths: list[list[tuple[float, float]]] = []
    current: list[tuple[float, float]] = []

    def grow(pts):
        """Extend the run and charge the density budget as we go.

        Charging only at the end of the pass left the grid empty while travel
        decisions were being made, so the cap never bit during the fill.
        """
        current.extend(pts)
        if density is not None:
            density.add(pts)

    for ri, line in enumerate(lines):
        # Tatami stagger: rotate the penetration phase row by row.
        phase = ((ri % stagger_rows) / stagger_rows) if stagger_rows > 1 else 0.0
        for p0, p1 in line:
            if not current:
                current = [p0]
                grow(_subdivide(p0, p1, max_len_px, phase))
                continue

            gap = math.dist(current[-1], p0)
            # A very short hop is a "bridge": standard practice, invisible on
            # fabric, and it saves a trim. Anything longer must stay inside the
            # shape or it would sew across a hole.
            ok = gap <= break_px and (
                gap <= bridge_px or _connector_inside(mask, current[-1], p0)
            )
            if ok:
                grow(_subdivide(current[-1], p0, max_len_px))
            else:
                walk: list[tuple[float, float]] = []
                detour = (_travel_path(mask, current[-1], p0, travel_px, density, avoid_weight)
                          if travel_px else None)
                if detour:
                    for a, b in zip(detour, detour[1:]):
                        walk.extend(_subdivide(a, b, max_len_px))
                # Refuse a detour that would pile thread onto ground already
                # heavily stitched — jumping there is the lesser evil, and
                # over-dense areas break thread and needles.
                if walk and not (density and density.would_exceed(walk)):
                    grow(walk)
                else:
                    if len(current) > 1:
                        paths.append(current)
                    current = [p0]
            # Stagger applies to the fill row itself; connectors and detours
            # keep plain even spacing since they are travel, not coverage.
            grow(_subdivide(p0, p1, max_len_px, phase))

    if len(current) > 1:
        paths.append(current)
    return paths


def _filter_short(path: list, min_px: float) -> list:
    """Drop points that would produce a stitch shorter than `min_px`.

    Serpentine fills naturally create a very short stitch at every row turn, and
    path simplification leaves short tails. Below ~0.5 mm the needle re-enters
    almost the same hole and the thread is worked through the eye without
    advancing, which weakens it until it snaps on the next long move. The final
    point is always kept so the path still ends where it should.
    """
    if len(path) < 3:
        return path
    out = [path[0]]
    for pt in path[1:-1]:
        if math.dist(out[-1], pt) >= min_px:
            out.append(pt)
    last = path[-1]
    # If dropping left the tail too short, replace rather than append, so we
    # never reintroduce the stitch we were trying to remove.
    if len(out) > 1 and math.dist(out[-1], last) < min_px:
        out[-1] = last
    else:
        out.append(last)
    return out


def _add_locks(path: list, lock_px: float) -> list:
    """Bracket a run with tie-in and tie-off stitches.

    A tie is a short there-and-back along the run's own direction, so it hides
    under the stitching that follows rather than showing as a spur.
    """
    if len(path) < 2 or lock_px <= 0:
        return path

    def leg(anchor, toward):
        d = math.dist(anchor, toward)
        if d < 1e-6:
            return None
        f = min(1.0, lock_px / d)
        return (anchor[0] + (toward[0] - anchor[0]) * f,
                anchor[1] + (toward[1] - anchor[1]) * f)

    out = []
    a = leg(path[0], path[1])
    if a:
        # Out only — `path` already begins at path[0], so returning here as well
        # would emit the same point twice and produce a zero-length stitch.
        out.extend([path[0], a])
    out.extend(path)
    b = leg(path[-1], path[-2])
    if b:
        out.extend([b, path[-1]])           # tie-off
    return out


def _path_length(path: list) -> float:
    return sum(math.dist(a, b) for a, b in zip(path, path[1:]))


def _resample_contour(contour, step_px: float) -> list[tuple[float, float]]:
    out = [contour[0]]
    acc = 0.0
    for a, b in zip(contour, contour[1:]):
        seg = math.dist(a, b)
        acc += seg
        if acc >= step_px:
            out.append(b)
            acc = 0.0
    if out[-1] != contour[-1]:
        out.append(contour[-1])
    return out


# --------------------------------------------------------------------------- #
# Public entry point


def trace(
    image_path: str | Path,
    output_path: str | Path,
    settings: TraceSettings | None = None,
) -> TraceReport:
    s = settings or TraceSettings()
    image_path, output_path = Path(image_path), Path(output_path)

    img, mm_per_px = _load_and_fit(image_path, s)
    if s.remove_background:
        img = _strip_background(img, s.bg_tolerance)
    img = img.filter(ImageFilter.MedianFilter(3))

    idx, threads, quant_error = _quantise(img, s.colors)

    report = TraceReport()
    report.width_mm = img.width * mm_per_px
    report.height_mm = img.height * mm_per_px
    report.quant_error = round(quant_error, 1)
    if quant_error > 40:
        report.notes.append(
            f"Colour fit is poor (error {quant_error:.0f}/255). This image is "
            f"photographic or heavily shaded — embroidery cannot reproduce it. "
            f"Use flat artwork, or expect a muddy result."
        )
    elif quant_error > 22:
        report.notes.append(
            f"Moderate colour fit (error {quant_error:.0f}/255). Consider more "
            f"--colors, or simplify the artwork."
        )

    spacing_px = s.density_mm / mm_per_px
    underlay_px = s.underlay_density_mm / mm_per_px
    max_len_px = s.stitch_len_mm / mm_per_px
    min_px = int(s.min_region_mm2 / (mm_per_px ** 2))

    pattern = pe.EmbPattern()
    # Centre the design on the origin; the machine centres it in the hoop.
    cx, cy = img.width / 2.0, img.height / 2.0
    break_px = 6.0 / mm_per_px    # travel further than 6 mm -> trim rather than drag
    bridge_px = s.bridge_mm / mm_per_px   # hops this short skip the inside test
    travel_px = s.travel_mm / mm_per_px   # max detour length when routing round a hole

    def to_machine(px_, py_):
        # pyembroidery works in 1/10 mm.
        return ((px_ - cx) * mm_per_px * 10.0, (py_ - cy) * mm_per_px * 10.0)

    # Collect first, write second: one thread and one contiguous block per
    # colour, otherwise every path becomes a colour change and PES overflows its
    # 255-colour-change ceiling.
    # Build every colour's mask first, so pull compensation can be resolved
    # BETWEEN colours before any stitching is planned.
    #
    # Dilating each colour independently makes both sides of a shared boundary
    # claim the same 0.4 mm band, and each lays underlay + fill + outline there.
    # Measured on real artwork: 83% of all over-dense cells — and every one of
    # the eight worst — sat exactly on a colour boundary. The later colour is
    # driving its needle into a band already packed with the earlier colour's
    # thread, which is the manual's "three or more overlapping stitches" and a
    # reliable way to snap needles late in a design.
    #
    # Resolution: the colour stitched LAST owns the seam. Earlier colours are
    # trimmed out of it, so no cell carries two colours' worth of passes, while
    # each colour still pulls outward into bare fabric so no gap opens.
    raw_masks: dict[int, np.ndarray] = {}
    areas: dict[int, float] = {}
    for colour_i in range(len(threads)):
        m = idx == colour_i
        if not m.any():
            continue
        m, dropped = _clean_mask(m, min_px)
        report.dropped_regions += dropped
        if not m.any():
            continue
        areas[colour_i] = float(m.sum()) * mm_per_px ** 2
        grow = int(round(s.pull_comp_mm / mm_per_px))
        raw_masks[colour_i] = (ndimage.binary_dilation(m, iterations=grow)
                               if grow > 0 else m)

    def _luma_of(ci):
        h = threads[ci]["hex"].lstrip("#")
        return (0.2126 * int(h[0:2], 16) + 0.7152 * int(h[2:4], 16)
                + 0.0722 * int(h[4:6], 16))

    stitch_order = sorted(raw_masks, key=_luma_of, reverse=True)
    for pos, ci in enumerate(stitch_order):
        for later in stitch_order[pos + 1:]:
            raw_masks[ci] = raw_masks[ci] & ~raw_masks[later]

    layers: list[tuple[dict, float, list]] = []
    for colour_i in stitch_order:
        mask = raw_masks[colour_i]
        if not mask.any():
            continue
        # Area of the artwork itself, before pull compensation inflated it and
        # before the seam was handed to a later colour.
        area_mm2 = areas[colour_i]

        # Fill each connected shape on its own, in nearest-neighbour order.
        #
        # Sweeping scan lines across the whole colour layer makes every line
        # cross every disconnected shape, so the needle ping-pongs across the
        # design and the trim count explodes — which is what a machine's preview
        # renders as scribble. Filling one shape at a time keeps travel local.
        paths: list[list[tuple[float, float]]] = []
        # One density budget per colour layer, shared across components and
        # across the underlay and fill passes.
        density = _Density(mask.shape, mm_per_px, s.max_density_per_mm2)
        labels, n_comp = ndimage.label(mask)
        components = []
        for comp in range(1, n_comp + 1):
            sub = labels == comp
            ys_, xs_ = np.nonzero(sub)
            components.append((sub, (xs_.mean(), ys_.mean())))

        ordered, remaining = [], list(range(len(components)))
        cur = np.array([0.0, 0.0])
        while remaining:
            j = min(remaining,
                    key=lambda i: (components[i][1][0] - cur[0]) ** 2
                    + (components[i][1][1] - cur[1]) ** 2)
            remaining.remove(j)
            ordered.append(j)
            cur = np.array(components[j][1])

        for j in ordered:
            sub = components[j][0]
            angle = s.fill_angle_deg
            if s.auto_angle:
                angle, _ = _best_fill_angle(sub, spacing_px)

            # Feed ALL fragments of a component through in one call, ordered
            # nearest-neighbour, rather than one call each. Fragments of a
            # component are connected in the mask, so the gap between the end of
            # one and the start of the next is a candidate for travel routing
            # too — calling per fragment forced every one of those gaps to
            # become a jump.
            def _fill_pass(scan_angle, spacing):
                frags = _order_fragments(
                    _scanline_fragments(sub, scan_angle, spacing))
                rows = [row for frag in frags for row in frag]
                if not rows:
                    return []
                return _lines_to_paths(sub, rows, max_len_px, break_px,
                                       bridge_px, travel_px, s.stagger_rows,
                                       density, s.travel_avoid_weight)

            if s.underlay:
                inset = int(round(s.underlay_inset_mm / mm_per_px))
                under_mask = (ndimage.binary_erosion(sub, iterations=inset)
                              if inset > 0 else sub)
                if under_mask.any():
                    outer, sub = sub, under_mask
                    paths += _fill_pass(angle + 90, underlay_px)
                    sub = outer
            paths += _fill_pass(angle, spacing_px)
        # Outline last so it sits over the fill and hides its stepped edges.
        if s.outline:
            outline_step = max(1.0, s.outline_stitch_mm / mm_per_px)
            for contour in _trace_contours(mask):
                pts = _resample_contour(contour, outline_step)
                if len(pts) >= 3:
                    paths.append(pts + [pts[0]])

        # Clean each run, then anchor it. Order matters: filter first so a tie
        # is never built from points the filter would have removed, and drop
        # runs too short to be worth the trim that reaching them costs.
        min_stitch_px = s.min_stitch_mm / mm_per_px
        min_path_px = s.min_path_mm / mm_per_px
        lock_px = s.lock_mm / mm_per_px
        cleaned = []
        for p_ in paths:
            if len(p_) < 2:
                continue
            p_ = _filter_short(p_, min_stitch_px)
            if len(p_) < 2 or _path_length(p_) < min_path_px:
                continue
            if s.lock_stitches:
                p_ = _add_locks(p_, lock_px)
            cleaned.append(p_)
        paths = cleaned
        if paths:
            layers.append((threads[colour_i], area_mm2, paths))

    # Stitch light colours first, dark last.
    #
    # Cluster index order is arbitrary, which left the sequence up to chance.
    # Dark thread covers a light neighbour's edge cleanly; light thread over dark
    # shows every stray dark stitch underneath. Because pull compensation makes
    # neighbouring colours overlap deliberately, whichever colour goes last owns
    # the boundary — so it should be the dark one, which is also usually the
    # outline colour.
    def _luma(layer):
        h = layer[0]["hex"].lstrip("#")
        r, g, b = int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)
        return 0.2126 * r + 0.7152 * g + 0.0722 * b

    layers.sort(key=_luma, reverse=True)

    total_layers = len(layers)
    trim_px = s.trim_mm / mm_per_px
    for li, (thread, area_mm2, paths) in enumerate(layers):
        pattern.add_thread(thread["hex"])
        count = 0
        last_pt = None
        for pi, path in enumerate(paths):
            x0, y0 = to_machine(*path[0])
            if pi:
                # Trim only for real travel; short hops carry the thread.
                #
                # NOTE this has no effect on PES/PEC output. pyembroidery's
                # pec_encode ignores TRIM commands outright and encodes every
                # jump after the first as a trim-jump, so PEC trim count always
                # equals jump count. It does matter for DST and other formats
                # that honour TRIM. The only way to cut trims in a PES is to cut
                # the number of jumps.
                if last_pt is None or math.dist(last_pt, path[0]) > trim_px:
                    pattern.trim()
            pattern.add_stitch_absolute(pe.JUMP, x0, y0)
            for px_, py_ in path:
                mx, my = to_machine(px_, py_)
                pattern.add_stitch_absolute(pe.STITCH, mx, my)
                count += 1
            last_pt = path[-1]
        if li < total_layers - 1:
            pattern.color_change()
        report.layers.append(
            {"thread": thread, "area_mm2": round(area_mm2, 1), "stitches": count}
        )

    if not report.layers:
        raise ValueError(
            "Nothing to stitch. The image may be entirely background, or every "
            "region fell below --min-region."
        )

    pattern.end()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    from . import convert as _convert

    if output_path.suffix.lower() == ".pes":
        # write_pes handles both Brother quirks: the origin convention (PEC
        # coordinates must start at 0,0, not straddle it) and pyembroidery's
        # PES section, which is laid out for a 130x180 hoop.
        _convert.write_pes(pattern, output_path)
    else:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        pe.write(pattern, str(output_path), {})

    report.total_stitches = pattern.count_stitch_commands(pe.STITCH)
    # Report the real stitched extent, not the image canvas — a circle on a
    # square canvas is smaller than the canvas, and the extent is what has to
    # fit the hoop.
    min_x, min_y, max_x, max_y = pattern.bounds()
    report.width_mm = round(prof.units_to_mm(max_x - min_x), 1)
    report.height_mm = round(prof.units_to_mm(max_y - min_y), 1)
    if total_layers >= 6:
        report.notes.append(
            f"{total_layers} colours means {total_layers - 1} manual rethreads."
        )
    return report
